export const brandGroupsMap = [
  ['SANGSIN', 'HI-Q', 'SANGSIN BRAKE'],
  ['GAZPROMNEFT', 'G-ENERGY', 'GAZPROM', 'ГАЗПРОМНЕФТЬ'],
  ['hans-pries', 'topran'],
  ['KNECHT', 'MAHLE', 'mahle/knecht', 'mahle original'],
  ['Белебей', 'БЗАК'],
  ['змз', 'дайдо металл русь', 'дайдо метал'],
  ['lada', 'ваз', 'вис', 'оат', 'лада-имидж', 'lada image'],
  ['HYUNDAI', 'KIA', 'MOBIS'],
  ['total', 'TotalEnergies'],
  ['gaz', 'g-part'],
  ['general motors', 'gm', 'opel'],
  ['sct', 'sct germany'],
  ['вмп', 'вмп авто', 'вмпавто', 'vmp', 'vmpauto'],
  ['pmc', 'x2', 'parts-mall', 'pm'],
  ['clearLight', 'ledo'],
  ['вати', 'вати-авто'],
  ['омега', 'группа омега'],
  ['невский фильтр', 'nevsky filter'],
  ['автопартнер', 'avp', 'autopartner'],
  ['lynx-auto', 'lynx'],
  ['автоград', 'автоград-д'],
  ['reinz', 'victor reinz'],
  ['AT', 'AT Program'],
];
